# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hebe.proto',
  package='hebe',
  serialized_pb='\n\nhebe.proto\x12\x04hebe\"\x8e\x01\n\x0b\x44\x61taPartial\x12\x17\n\x04name\x18\x01 \x02(\t:\tinputdata\x12 \n\x07\x63olumns\x18\x02 \x02(\t:\x0fpvid,deliver_id\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\x17\n\x07\x63onvert\x18\x04 \x02(\t:\x06\x31\x30\x30\x30\x30\x30\x12\x0e\n\x06\x64tfrom\x18\x05 \x01(\t\x12\r\n\x05table\x18\x06 \x02(\t\"*\n\x06Shrink\x12\x12\n\x04name\x18\x01 \x02(\t:\x04null\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\"C\n\x05Noise\x12\x0f\n\x07\x63olumns\x18\x01 \x02(\t\x12\n\n\x02to\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t\x12\x0e\n\x06\x66\x61\x63tor\x18\x04 \x02(\t\"T\n\tTransform\x12\x12\n\x04type\x18\x01 \x02(\t:\x04null\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x03 \x02(\t\x12\x14\n\x05label\x18\x04 \x01(\t:\x05\x63lick\"l\n\tIntersect\x12\x0f\n\x07\x63olumns\x18\x01 \x02(\t\x12\x12\n\nfix_bundle\x18\x02 \x01(\t\x12\x11\n\x06\x66\x61\x63tor\x18\x03 \x01(\x05:\x01\x32\x12\x11\n\x07mapfile\x18\x04 \x01(\t:\x00\x12\x14\n\x05label\x18\x05 \x01(\t:\x05\x63lick\"E\n\x06\x46ormat\x12\x10\n\x04name\x18\x01 \x02(\t:\x02vw\x12\x0f\n\x07pattern\x18\x02 \x02(\t\x12\x18\n\rvalidate_rate\x18\x03 \x01(\x05:\x01\x30\"o\n\x06\x46ilter\x12\x12\n\x04name\x18\x01 \x02(\t:\x04null\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\x12\x0e\n\x06inputs\x18\x03 \x02(\t\x12\x0f\n\x07outputs\x18\x04 \x02(\t\x12\x12\n\noutput_num\x18\x05 \x01(\x05\x12\x0e\n\x06offset\x18\x06 \x01(\x05\"\xe9\x01\n\x08Settings\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\thdfs_path\x18\x02 \x02(\t\x12\"\n\x07partial\x18\x03 \x03(\x0b\x32\x11.hebe.DataPartial\x12\x1c\n\x06shrink\x18\x04 \x03(\x0b\x32\x0c.hebe.Shrink\x12\x1a\n\x05noise\x18\x05 \x03(\x0b\x32\x0b.hebe.Noise\x12\"\n\ttransform\x18\x06 \x03(\x0b\x32\x0f.hebe.Transform\x12\x1c\n\x06\x66ilter\x18\x07 \x03(\x0b\x32\x0c.hebe.Filter\x12\x1c\n\x06\x66ormat\x18\x08 \x03(\x0b\x32\x0c.hebe.Format')




_DATAPARTIAL = descriptor.Descriptor(
  name='DataPartial',
  full_name='hebe.DataPartial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='hebe.DataPartial.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("inputdata", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='columns', full_name='hebe.DataPartial.columns', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("pvid,deliver_id", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='hebe.DataPartial.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='convert', full_name='hebe.DataPartial.convert', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("100000", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dtfrom', full_name='hebe.DataPartial.dtfrom', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='table', full_name='hebe.DataPartial.table', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=163,
)


_SHRINK = descriptor.Descriptor(
  name='Shrink',
  full_name='hebe.Shrink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='hebe.Shrink.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("null", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='args', full_name='hebe.Shrink.args', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=165,
  serialized_end=207,
)


_NOISE = descriptor.Descriptor(
  name='Noise',
  full_name='hebe.Noise',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='columns', full_name='hebe.Noise.columns', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to', full_name='hebe.Noise.to', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='hebe.Noise.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='factor', full_name='hebe.Noise.factor', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=209,
  serialized_end=276,
)


_TRANSFORM = descriptor.Descriptor(
  name='Transform',
  full_name='hebe.Transform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='hebe.Transform.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("null", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='args', full_name='hebe.Transform.args', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='columns', full_name='hebe.Transform.columns', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='hebe.Transform.label', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("click", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=278,
  serialized_end=362,
)


_INTERSECT = descriptor.Descriptor(
  name='Intersect',
  full_name='hebe.Intersect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='columns', full_name='hebe.Intersect.columns', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fix_bundle', full_name='hebe.Intersect.fix_bundle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='factor', full_name='hebe.Intersect.factor', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mapfile', full_name='hebe.Intersect.mapfile', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='hebe.Intersect.label', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("click", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=364,
  serialized_end=472,
)


_FORMAT = descriptor.Descriptor(
  name='Format',
  full_name='hebe.Format',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='hebe.Format.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("vw", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pattern', full_name='hebe.Format.pattern', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='validate_rate', full_name='hebe.Format.validate_rate', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=474,
  serialized_end=543,
)


_FILTER = descriptor.Descriptor(
  name='Filter',
  full_name='hebe.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='hebe.Filter.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("null", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='args', full_name='hebe.Filter.args', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inputs', full_name='hebe.Filter.inputs', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='outputs', full_name='hebe.Filter.outputs', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='output_num', full_name='hebe.Filter.output_num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='hebe.Filter.offset', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=545,
  serialized_end=656,
)


_SETTINGS = descriptor.Descriptor(
  name='Settings',
  full_name='hebe.Settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='hebe.Settings.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hdfs_path', full_name='hebe.Settings.hdfs_path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partial', full_name='hebe.Settings.partial', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shrink', full_name='hebe.Settings.shrink', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='noise', full_name='hebe.Settings.noise', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transform', full_name='hebe.Settings.transform', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter', full_name='hebe.Settings.filter', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='format', full_name='hebe.Settings.format', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=659,
  serialized_end=892,
)

_SETTINGS.fields_by_name['partial'].message_type = _DATAPARTIAL
_SETTINGS.fields_by_name['shrink'].message_type = _SHRINK
_SETTINGS.fields_by_name['noise'].message_type = _NOISE
_SETTINGS.fields_by_name['transform'].message_type = _TRANSFORM
_SETTINGS.fields_by_name['filter'].message_type = _FILTER
_SETTINGS.fields_by_name['format'].message_type = _FORMAT
DESCRIPTOR.message_types_by_name['DataPartial'] = _DATAPARTIAL
DESCRIPTOR.message_types_by_name['Shrink'] = _SHRINK
DESCRIPTOR.message_types_by_name['Noise'] = _NOISE
DESCRIPTOR.message_types_by_name['Transform'] = _TRANSFORM
DESCRIPTOR.message_types_by_name['Intersect'] = _INTERSECT
DESCRIPTOR.message_types_by_name['Format'] = _FORMAT
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER
DESCRIPTOR.message_types_by_name['Settings'] = _SETTINGS

class DataPartial(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATAPARTIAL
  
  # @@protoc_insertion_point(class_scope:hebe.DataPartial)

class Shrink(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SHRINK
  
  # @@protoc_insertion_point(class_scope:hebe.Shrink)

class Noise(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOISE
  
  # @@protoc_insertion_point(class_scope:hebe.Noise)

class Transform(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSFORM
  
  # @@protoc_insertion_point(class_scope:hebe.Transform)

class Intersect(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTERSECT
  
  # @@protoc_insertion_point(class_scope:hebe.Intersect)

class Format(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMAT
  
  # @@protoc_insertion_point(class_scope:hebe.Format)

class Filter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILTER
  
  # @@protoc_insertion_point(class_scope:hebe.Filter)

class Settings(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETTINGS
  
  # @@protoc_insertion_point(class_scope:hebe.Settings)

# @@protoc_insertion_point(module_scope)
